# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoseNet-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoseNet
  pod 'TensorSwift', '~> 0.2'
  
  pod 'SwiftyJSON', '~> 4.0'
  
  pod 'CSV.swift', '~> 2.3.1'

end
